### ISSUE TITLE
[Jsecond] Методы

### ISSUE THREAD

**Issue by pavel-b-novikov** [Glavak/JsConverter#1]
```csharp
if (node.Method.Name == "Select" &&
                node.Method.Module.Assembly == Assembly.GetAssembly(typeof(System.Linq.Enumerable)))
```

Вы реально считаете что этого достаточно?

**Comment by Glavak** [comment]
Вроде бы больше там методов с таким названием нет. Но согласен что решение не очень, лучше сравнивать сам `node.Method` с `typeof(Enumerable).GetMethod(...)`
Залил фикс в репозиторий

**Comment by pavel-b-novikov** [comment]
Ай, ладно. Пущай будет.
